### PR TITLE
CC-5 # Make deploy only upload new or updated files

### PR DESCRIPTION
**Pull request by simonmarklar**
- Added filtering functionality to trim the list of files to be uploaded
- Added relevant tests

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Noticed that you're using `fs.lstatSync()` instead of `fs.lstat(cb)`. This is probably fine for a CLI. If this were a web service or an app, then the asynchronous call would be more appropriate.

**Comment by jokeyrhyme** [comment]
I wonder if this might be useful, maybe not now but later? https://github.com/MathieuLoutre/mock-aws-s3

**Comment by simonmarklar** [comment]
For anything that has a significant amount of latency I will use the async methods. I think with the relatively small amount of files the sync method works well here, and makes the code less complicated.

Perhaps there's a call for putting in some performance tests, seeing how long it takes to list and stat 100, 500, 1000 files. I'll add that in.

**Comment by simonmarklar** [comment]
@jokeyrhyme are you happy for this to be merged? Some more tasks need to be done but I think they should be separate PRs

**Comment by simonmarklar** [comment]
ah crap, just realised this is going to merge into master, but it should be merging with develop. looks like i need to make another PR and use the right branch

**Comment by jokeyrhyme** [comment]
You can change the default branch in the GitHub project settings. For Git Flow projects, the default branch should probably be develop.

**Pull request closed without merging**
